development:
  adapter: jdbcderby
  hostname: localhost
  database: db/development

test:
  adapter: jdbcderby
  hostname: localhost
  database: db/test

production:
  adapter: jdbcderby
  hostname: localhost
  database: db/production
