development:
  adapter: jdbcmysql
  hostname: localhost
  database: laf_dev
  username: laf
  password: laf

test:
  adapter: jdbcmysql
  hostname: localhost
  database: laf_test
  username: laf
  password: laf

production:
  adapter: jdbcmysql
  hostname: localhost
  database: laf
  port: 3307
  username: laf
  password: laf
