development:
  adapter: jdbcmysql
  hostname: localhost
  database: laf_dev
  username: laf
  password: laf

test:
  adapter: jdbcmysql
  hostname: localhost
  database: laf_test
  username: laf
  password: laf

production:
  adapter: jdbcderby
  hostname: localhost
  database: db/production
